site_name: 'IPFS Publish - Documentation'
site_description: 'Publish your static webpages directly from Git - automatically!'
site_author: 'Adam Uhlíř'

copyright: 'Copyright &copy; 2019 <a href="https://www.adam-uhlir.me">Adam Uhlíř</a>'

repo_name: 'auhau/ipfs-publish'
repo_url: 'https://github.com/auhau/ipfs-publish'
theme:
  name: 'material'
  palette:
    primary: 'orange'
    accent: 'orange'
  logo:
    icon: 'power_settings_new'

extra_css:
  - 'stylesheets/one-page.css'

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.superfences

google_analytics:
  - UA-69422360-3
  - auto

nav:
  - Home: 'index.md'